// DO NOT EDIT
// Generated by JFlex 1.8.2 http://jflex.de/
// source: src/main/java/gt/edu/url/compiladores/loop/interprete/loop/interprete/intermedio.flex



package gt.edu.url.compiladores.loop.interprete.loop.interprete;
import java_cup.runtime.Symbol; 

// See https://github.com/jflex-de/jflex/issues/222
@SuppressWarnings("FallThrough")
class intermedio implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\1\u0100\1\u0200\35\u0300\1\u0400\267\u0300\10\u0500\u1020\u0300";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\4\1\5"+
    "\1\6\2\7\1\10\1\7\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\12\22\1\7\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\32\2\33"+
    "\1\34\14\33\1\35\10\33\1\7\1\11\1\7\1\36"+
    "\1\37\1\40\1\41\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\1\50\1\51\2\50\1\52\1\53\1\54\1\55"+
    "\2\50\1\56\1\57\1\60\1\50\1\61\3\50\1\62"+
    "\1\7\1\63\2\7\6\0\1\3\33\0\1\7\22\0"+
    "\1\64\12\0\1\64\1\0\1\65\1\27\1\66\5\0"+
    "\1\65\3\0\1\65\3\0\1\65\1\0\1\65\6\0"+
    "\1\65\1\0\1\65\4\0\1\67\7\0\1\67\3\0"+
    "\1\67\3\0\1\67\1\0\1\67\6\0\1\67\1\0"+
    "\1\67\303\0\1\40\2\0\1\40\365\0\1\66\12\0"+
    "\1\40\u0163\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1536];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\4\1\5\3\6\1\7\1\10"+
    "\1\11\2\7\1\12\1\7\1\13\1\7\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\14\22\1\4\1\6\1\0"+
    "\1\23\1\6\1\0\1\24\2\6\1\25\1\14\1\26"+
    "\1\27\1\6\1\0\2\21\1\6\1\21\1\20\1\21"+
    "\23\22\1\0\1\24\1\6\3\0\1\6\1\30\1\6"+
    "\17\22\1\31\3\22\1\32\1\33\1\26\12\22\1\34"+
    "\1\22\1\35\1\36\1\37\3\22\1\0\1\33\10\22"+
    "\1\40\2\22\1\41\2\22\1\0\1\22\1\42\1\43"+
    "\2\22\1\44\6\22\1\0\1\45\11\22\1\1\6\22"+
    "\1\46\2\22\1\47\3\22\1\50\1\51\1\52\1\22"+
    "\1\53\6\22\1\54\1\55\3\22\1\56\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[196];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\70\0\70\0\160\0\250\0\340\0\u0118\0\u0150"+
    "\0\u0150\0\70\0\70\0\70\0\u0188\0\70\0\u01c0\0\70"+
    "\0\u01f8\0\u0230\0\70\0\u0150\0\340\0\u0268\0\u02a0\0\u02d8"+
    "\0\u0310\0\u0348\0\u0380\0\u03b8\0\u03f0\0\u0428\0\u0460\0\u0498"+
    "\0\u04d0\0\u0508\0\u0540\0\u0578\0\u05b0\0\u05e8\0\u0150\0\u0620"+
    "\0\u0658\0\u0150\0\u0690\0\u06c8\0\u0150\0\u0700\0\u0738\0\u0770"+
    "\0\u07a8\0\u07e0\0\u0818\0\u0850\0\u0888\0\u08c0\0\u08f8\0\u0930"+
    "\0\u0968\0\u09a0\0\u09d8\0\u0a10\0\u0a48\0\u0a80\0\u0ab8\0\u0af0"+
    "\0\u0b28\0\u0b60\0\u0b98\0\u0bd0\0\u0c08\0\u0c40\0\u0c78\0\u0cb0"+
    "\0\u0ce8\0\u0d20\0\u0d58\0\u0d90\0\70\0\u0dc8\0\u0e00\0\u0e38"+
    "\0\u0e70\0\u0ea8\0\u07e0\0\u0ee0\0\u0f18\0\u0f50\0\u0f88\0\u0fc0"+
    "\0\u0ff8\0\u1030\0\u1068\0\u10a0\0\u10d8\0\u1110\0\u1148\0\u1180"+
    "\0\u11b8\0\u11f0\0\u1228\0\70\0\u1260\0\u1298\0\u12d0\0\u1308"+
    "\0\u0e00\0\u1340\0\u1378\0\u13b0\0\u13e8\0\u1420\0\u1458\0\u1490"+
    "\0\u14c8\0\u1500\0\u1538\0\u1570\0\u02d8\0\u15a8\0\u02d8\0\u02d8"+
    "\0\u02d8\0\u15e0\0\u1618\0\u1650\0\u1688\0\u0e70\0\u16c0\0\u16f8"+
    "\0\u1730\0\u1768\0\u17a0\0\u17d8\0\u1810\0\u1848\0\u02d8\0\u1880"+
    "\0\u18b8\0\70\0\u18f0\0\u1928\0\u1960\0\u1998\0\u19d0\0\u02d8"+
    "\0\u1a08\0\u1a40\0\u02d8\0\u1a78\0\u1ab0\0\u1ae8\0\u1b20\0\u1b58"+
    "\0\u1b90\0\u1bc8\0\u02d8\0\u1c00\0\u1c38\0\u1c70\0\u1ca8\0\u1ce0"+
    "\0\u1d18\0\u1d50\0\u1d88\0\u1dc0\0\u1308\0\u1df8\0\u1e30\0\u1e68"+
    "\0\u1ea0\0\u1ed8\0\u1f10\0\u02d8\0\u1f48\0\u1f80\0\u02d8\0\u1fb8"+
    "\0\u1ff0\0\u2028\0\70\0\70\0\70\0\u2060\0\u02d8\0\u2098"+
    "\0\u20d0\0\u2108\0\u2140\0\u2178\0\u21b0\0\u0f18\0\70\0\u21e8"+
    "\0\u2220\0\u2258\0\u0f18\0\u0f18";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[196];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\0\1\5\1\6\1\7\1\10"+
    "\1\11\1\10\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\25\1\24\2\2"+
    "\5\26\1\11\1\27\1\10\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\2\30\1\36\1\37\3\30\1\40\1\41"+
    "\1\42\1\43\1\30\1\44\1\10\1\45\1\2\1\10"+
    "\72\0\1\4\60\0\1\4\10\0\1\46\70\0\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\2\10\1\0\1\10"+
    "\1\47\1\10\2\0\5\45\1\10\1\45\1\10\22\50"+
    "\2\10\1\45\1\0\1\10\1\0\1\51\2\0\1\51"+
    "\1\7\1\52\1\7\2\10\3\51\1\7\1\51\1\7"+
    "\1\51\2\7\1\51\3\7\2\51\5\53\1\7\1\53"+
    "\1\10\22\54\2\7\1\45\1\0\1\10\5\0\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\2\10\1\0\3\10"+
    "\2\0\5\45\1\10\1\45\1\10\22\50\2\10\1\45"+
    "\1\0\1\10\5\0\5\10\3\0\1\55\1\0\1\10"+
    "\1\0\2\10\1\0\3\10\2\0\5\45\1\10\1\45"+
    "\1\10\22\50\2\10\1\45\1\0\1\10\5\0\5\10"+
    "\3\0\1\10\1\0\1\55\1\0\1\10\1\56\1\0"+
    "\3\10\2\0\5\45\1\10\1\45\1\10\22\50\2\10"+
    "\1\45\1\0\1\10\14\0\1\57\4\0\1\60\53\0"+
    "\5\61\3\0\1\61\1\0\1\61\1\62\1\10\1\22"+
    "\1\0\3\61\2\0\5\63\1\61\1\27\1\61\22\64"+
    "\2\61\1\45\1\0\1\61\5\0\5\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\65\1\66\1\0\3\10\2\0"+
    "\5\26\1\10\1\27\1\10\22\67\2\10\1\45\1\0"+
    "\1\10\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\66\1\0\3\10\2\0\5\27\1\10\1\27"+
    "\1\10\22\70\2\10\1\45\1\0\1\10\5\0\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\1\65\1\71\1\0"+
    "\3\10\2\0\5\72\1\10\1\72\1\10\22\30\2\10"+
    "\1\72\1\0\1\71\5\0\5\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\65\1\71\1\0\3\10\2\0\5\72"+
    "\1\10\1\72\1\10\14\30\1\73\5\30\2\10\1\72"+
    "\1\0\1\71\5\0\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\65\1\71\1\0\3\10\2\0\5\72\1\10"+
    "\1\72\1\10\1\74\13\30\1\75\5\30\2\10\1\72"+
    "\1\0\1\71\5\0\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\65\1\71\1\0\3\10\2\0\5\72\1\10"+
    "\1\72\1\10\4\30\1\76\15\30\2\10\1\72\1\0"+
    "\1\71\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\11\30\1\77\1\30\1\100\2\30\1\101\3\30"+
    "\2\10\1\72\1\0\1\71\5\0\5\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\65\1\71\1\0\3\10\2\0"+
    "\5\72\1\10\1\72\1\10\1\102\21\30\2\10\1\72"+
    "\1\0\1\71\5\0\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\65\1\71\1\0\3\10\2\0\5\72\1\10"+
    "\1\72\1\10\13\30\1\103\6\30\2\10\1\72\1\0"+
    "\1\71\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\4\30\1\104\7\30\1\105\5\30\2\10\1\72"+
    "\1\0\1\71\5\0\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\65\1\71\1\0\3\10\2\0\5\72\1\10"+
    "\1\72\1\10\1\106\3\30\1\107\15\30\2\10\1\72"+
    "\1\0\1\71\5\0\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\65\1\71\1\0\3\10\2\0\5\72\1\10"+
    "\1\72\1\10\4\30\1\110\3\30\1\111\11\30\2\10"+
    "\1\72\1\0\1\71\5\0\5\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\65\1\71\1\0\3\10\2\0\5\72"+
    "\1\10\1\72\1\10\1\112\21\30\2\10\1\72\1\0"+
    "\1\71\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\4\30\1\113\15\30\2\10\1\72\1\0\1\71"+
    "\2\0\1\4\2\0\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\2\10\1\0\3\10\2\0\5\45\1\10\1\45"+
    "\1\10\22\50\1\44\1\10\1\45\1\0\1\10\5\0"+
    "\5\10\3\0\1\10\1\0\1\10\1\0\1\65\1\10"+
    "\1\0\3\10\2\0\5\45\1\10\1\45\1\10\22\0"+
    "\2\10\1\45\1\0\1\10\4\0\1\114\70\0\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\1\65\1\10\1\0"+
    "\3\10\2\0\5\45\1\10\1\45\1\10\22\50\2\10"+
    "\1\45\1\0\1\10\1\0\1\51\2\0\2\51\1\115"+
    "\1\51\2\0\26\51\1\0\24\51\4\0\1\51\2\0"+
    "\1\51\1\7\1\52\1\7\2\10\3\51\1\7\1\51"+
    "\1\7\1\51\1\116\1\7\1\51\3\7\2\51\5\53"+
    "\1\7\1\53\1\10\22\51\2\7\1\45\1\0\1\10"+
    "\1\0\1\51\2\0\1\51\1\7\1\52\1\7\2\10"+
    "\3\51\1\7\1\51\1\7\1\51\1\116\1\7\1\51"+
    "\3\7\2\51\5\53\1\7\1\53\1\10\22\54\2\7"+
    "\1\45\1\0\1\10\5\0\5\10\3\0\1\10\1\0"+
    "\1\10\1\62\1\10\1\56\1\0\3\10\2\0\5\45"+
    "\1\10\1\45\1\10\22\50\2\10\1\45\1\0\1\10"+
    "\4\0\1\117\5\57\2\0\1\120\1\57\1\117\1\57"+
    "\1\0\1\121\1\57\1\117\3\57\1\0\1\117\35\57"+
    "\1\117\1\57\4\0\6\60\2\0\4\60\1\0\6\60"+
    "\1\0\40\60\5\0\5\61\3\0\1\61\1\0\1\61"+
    "\1\0\2\10\1\0\3\61\2\0\5\122\1\61\1\45"+
    "\1\61\22\50\2\61\1\45\1\0\1\61\22\0\1\123"+
    "\52\0\5\61\3\0\1\61\1\0\1\61\1\0\1\124"+
    "\1\66\1\0\3\61\2\0\5\63\1\61\1\27\1\61"+
    "\22\70\2\61\1\45\1\0\1\61\5\0\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\66\1\0\3\10"+
    "\2\0\5\27\1\10\1\27\1\10\22\64\2\10\1\45"+
    "\1\0\1\10\21\0\1\65\53\0\5\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\10\1\66\1\0\3\10\2\0"+
    "\5\27\1\10\1\27\1\10\22\64\2\10\1\45\1\0"+
    "\1\10\22\0\1\70\6\0\5\67\1\0\1\70\1\0"+
    "\22\67\27\0\1\70\6\0\5\70\1\0\1\70\1\0"+
    "\22\70\12\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\10\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\22\30\2\10\1\72\1\0\1\71\5\0\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\1\65\1\71\1\0"+
    "\3\10\2\0\5\72\1\10\1\72\1\10\22\125\2\10"+
    "\1\72\1\0\1\71\5\0\5\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\65\1\71\1\0\3\10\2\0\5\72"+
    "\1\10\1\72\1\10\14\30\1\126\5\30\2\10\1\72"+
    "\1\0\1\71\5\0\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\65\1\71\1\0\3\10\2\0\5\72\1\10"+
    "\1\72\1\10\3\30\1\127\16\30\2\10\1\72\1\0"+
    "\1\71\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\16\30\1\130\3\30\2\10\1\72\1\0\1\71"+
    "\5\0\5\10\3\0\1\10\1\0\1\10\1\0\1\65"+
    "\1\71\1\0\3\10\2\0\5\72\1\10\1\72\1\10"+
    "\20\30\1\131\1\30\2\10\1\72\1\0\1\71\5\0"+
    "\5\10\3\0\1\10\1\0\1\10\1\0\1\65\1\71"+
    "\1\0\3\10\2\0\5\72\1\10\1\72\1\10\10\30"+
    "\1\132\11\30\2\10\1\72\1\0\1\71\5\0\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\1\65\1\71\1\0"+
    "\3\10\2\0\5\72\1\10\1\72\1\10\17\30\1\133"+
    "\2\30\2\10\1\72\1\0\1\71\5\0\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\71\1\0\3\10"+
    "\2\0\5\72\1\10\1\72\1\10\2\30\1\134\17\30"+
    "\2\10\1\72\1\0\1\71\5\0\5\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\65\1\71\1\0\3\10\2\0"+
    "\5\72\1\10\1\72\1\10\11\30\1\135\10\30\2\10"+
    "\1\72\1\0\1\71\5\0\5\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\65\1\71\1\0\3\10\2\0\5\72"+
    "\1\10\1\72\1\10\16\30\1\136\3\30\2\10\1\72"+
    "\1\0\1\71\5\0\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\65\1\71\1\0\3\10\2\0\5\72\1\10"+
    "\1\72\1\10\4\30\1\137\15\30\2\10\1\72\1\0"+
    "\1\71\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\6\30\1\140\13\30\2\10\1\72\1\0\1\71"+
    "\5\0\5\10\3\0\1\10\1\0\1\10\1\0\1\65"+
    "\1\71\1\0\3\10\2\0\5\72\1\10\1\72\1\10"+
    "\10\30\1\141\11\30\2\10\1\72\1\0\1\71\5\0"+
    "\5\10\3\0\1\10\1\0\1\10\1\0\1\65\1\71"+
    "\1\0\3\10\2\0\5\72\1\10\1\72\1\10\1\142"+
    "\21\30\2\10\1\72\1\0\1\71\5\0\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\71\1\0\3\10"+
    "\2\0\5\72\1\10\1\72\1\10\13\30\1\143\6\30"+
    "\2\10\1\72\1\0\1\71\4\0\1\144\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\71\1\0\3\10"+
    "\2\0\5\72\1\10\1\72\1\10\13\30\1\145\6\30"+
    "\2\10\1\72\1\0\1\71\5\0\5\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\65\1\71\1\0\3\10\2\0"+
    "\5\72\1\10\1\72\1\10\13\30\1\146\6\30\2\10"+
    "\1\72\1\0\1\71\5\0\5\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\65\1\71\1\0\3\10\2\0\5\72"+
    "\1\10\1\72\1\10\15\30\1\147\4\30\2\10\1\72"+
    "\1\0\1\71\4\0\1\150\64\0\1\51\2\0\2\51"+
    "\1\115\1\51\2\0\7\51\1\116\16\51\1\0\24\51"+
    "\7\0\6\117\2\0\1\120\3\117\1\0\6\117\1\0"+
    "\40\117\4\0\6\117\2\0\1\120\3\117\1\0\1\151"+
    "\5\117\1\0\40\117\4\0\6\57\2\0\1\152\3\57"+
    "\1\0\1\57\1\117\2\57\2\117\1\0\1\57\5\117"+
    "\2\57\23\117\1\57\2\117\1\57\1\117\5\0\5\61"+
    "\3\0\1\61\1\0\1\61\1\0\1\124\1\10\1\0"+
    "\3\61\2\0\5\122\1\61\1\45\1\61\22\0\2\61"+
    "\1\45\1\0\1\61\5\0\5\124\3\0\1\124\1\0"+
    "\1\124\1\0\2\124\1\0\3\124\7\0\1\124\1\0"+
    "\1\124\22\0\2\124\2\0\1\124\22\0\1\125\6\0"+
    "\5\125\1\0\1\125\1\0\22\125\2\0\1\125\1\0"+
    "\1\125\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\11\30\1\153\10\30\2\10\1\72\1\0\1\71"+
    "\5\0\5\10\3\0\1\10\1\0\1\10\1\0\1\65"+
    "\1\71\1\0\3\10\2\0\5\72\1\10\1\72\1\10"+
    "\4\30\1\154\15\30\2\10\1\72\1\0\1\71\5\0"+
    "\5\10\3\0\1\10\1\0\1\10\1\0\1\65\1\71"+
    "\1\0\3\10\2\0\5\72\1\10\1\72\1\10\4\30"+
    "\1\155\15\30\2\10\1\72\1\0\1\71\5\0\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\1\65\1\71\1\0"+
    "\3\10\2\0\5\72\1\10\1\72\1\10\14\30\1\156"+
    "\5\30\2\10\1\72\1\0\1\71\5\0\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\71\1\0\3\10"+
    "\2\0\5\72\1\10\1\72\1\10\12\30\1\157\7\30"+
    "\2\10\1\72\1\0\1\71\5\0\5\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\65\1\71\1\0\3\10\2\0"+
    "\5\72\1\10\1\72\1\10\4\30\1\160\7\30\1\161"+
    "\5\30\2\10\1\72\1\0\1\71\5\0\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\71\1\0\3\10"+
    "\2\0\5\72\1\10\1\72\1\10\15\30\1\162\4\30"+
    "\2\10\1\72\1\0\1\71\5\0\5\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\65\1\71\1\0\3\10\2\0"+
    "\5\72\1\10\1\72\1\10\16\30\1\163\3\30\2\10"+
    "\1\72\1\0\1\71\5\0\5\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\65\1\71\1\0\3\10\2\0\5\72"+
    "\1\10\1\72\1\10\17\30\1\164\2\30\2\10\1\72"+
    "\1\0\1\71\5\0\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\65\1\71\1\0\3\10\2\0\5\72\1\10"+
    "\1\72\1\10\15\30\1\165\4\30\2\10\1\72\1\0"+
    "\1\71\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\1\166\21\30\2\10\1\72\1\0\1\71\5\0"+
    "\5\10\3\0\1\10\1\0\1\10\1\0\1\65\1\71"+
    "\1\0\3\10\2\0\5\72\1\10\1\72\1\10\21\30"+
    "\1\167\2\10\1\72\1\0\1\71\5\0\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\71\1\0\3\10"+
    "\2\0\5\72\1\10\1\72\1\10\11\30\1\170\10\30"+
    "\2\10\1\72\1\0\1\71\5\0\5\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\65\1\71\1\0\3\10\2\0"+
    "\5\72\1\10\1\72\1\10\14\30\1\171\5\30\2\10"+
    "\1\72\1\0\1\71\5\0\5\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\65\1\71\1\0\3\10\2\0\5\72"+
    "\1\10\1\72\1\10\14\30\1\172\5\30\2\10\1\72"+
    "\1\0\1\71\5\0\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\65\1\71\1\0\3\10\2\0\5\72\1\10"+
    "\1\72\1\10\6\30\1\173\13\30\2\10\1\72\1\0"+
    "\1\71\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\3\30\1\174\16\30\2\10\1\72\1\0\1\71"+
    "\4\0\1\175\67\0\1\117\5\57\2\0\1\120\1\57"+
    "\1\117\1\57\1\0\1\176\1\57\1\117\3\57\1\0"+
    "\1\117\35\57\1\117\1\57\5\0\5\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\65\1\71\1\0\3\10\2\0"+
    "\5\72\1\10\1\72\1\10\4\30\1\177\15\30\2\10"+
    "\1\72\1\0\1\71\5\0\5\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\65\1\71\1\0\3\10\2\0\5\72"+
    "\1\10\1\72\1\10\13\30\1\200\6\30\2\10\1\72"+
    "\1\0\1\71\5\0\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\65\1\71\1\0\3\10\2\0\5\72\1\10"+
    "\1\72\1\10\13\30\1\201\6\30\2\10\1\72\1\0"+
    "\1\71\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\11\30\1\202\10\30\2\10\1\72\1\0\1\71"+
    "\5\0\5\10\3\0\1\10\1\0\1\10\1\0\1\65"+
    "\1\71\1\0\3\10\2\0\5\72\1\10\1\72\1\10"+
    "\10\30\1\203\11\30\2\10\1\72\1\0\1\71\5\0"+
    "\5\10\3\0\1\10\1\0\1\10\1\0\1\65\1\71"+
    "\1\0\3\10\2\0\5\72\1\10\1\72\1\10\15\30"+
    "\1\204\4\30\2\10\1\72\1\0\1\71\5\0\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\1\65\1\71\1\0"+
    "\3\10\2\0\5\72\1\10\1\72\1\10\13\30\1\205"+
    "\6\30\2\10\1\72\1\0\1\71\5\0\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\71\1\0\3\10"+
    "\2\0\5\72\1\10\1\72\1\10\10\30\1\206\11\30"+
    "\2\10\1\72\1\0\1\71\5\0\5\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\65\1\71\1\0\3\10\2\0"+
    "\5\72\1\10\1\72\1\10\14\30\1\207\5\30\2\10"+
    "\1\72\1\0\1\71\5\0\5\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\65\1\71\1\0\3\10\2\0\5\72"+
    "\1\10\1\72\1\10\1\210\21\30\2\10\1\72\1\0"+
    "\1\71\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\15\30\1\211\4\30\2\10\1\72\1\0\1\71"+
    "\4\0\1\212\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\22\30\2\10\1\72\1\0\1\71\5\0\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\1\65\1\71\1\0"+
    "\3\10\2\0\5\72\1\10\1\72\1\10\4\30\1\213"+
    "\15\30\2\10\1\72\1\0\1\71\5\0\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\71\1\0\3\10"+
    "\2\0\5\72\1\10\1\72\1\10\1\214\21\30\2\10"+
    "\1\72\1\0\1\71\4\0\1\215\70\0\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\71\1\0\3\10"+
    "\2\0\5\72\1\10\1\72\1\10\1\216\21\30\2\10"+
    "\1\72\1\0\1\71\5\0\5\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\65\1\71\1\0\3\10\2\0\5\72"+
    "\1\10\1\72\1\10\1\217\21\30\2\10\1\72\1\0"+
    "\1\71\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\14\30\1\220\5\30\2\10\1\72\1\0\1\71"+
    "\5\0\5\10\3\0\1\10\1\0\1\10\1\0\1\65"+
    "\1\71\1\0\3\10\2\0\5\72\1\10\1\72\1\10"+
    "\20\30\1\221\1\30\2\10\1\72\1\0\1\71\5\0"+
    "\5\10\3\0\1\10\1\0\1\10\1\0\1\65\1\71"+
    "\1\0\3\10\2\0\5\72\1\10\1\72\1\10\13\30"+
    "\1\222\6\30\2\10\1\72\1\0\1\71\5\0\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\1\65\1\71\1\0"+
    "\3\10\2\0\5\72\1\10\1\72\1\10\14\30\1\223"+
    "\5\30\2\10\1\72\1\0\1\71\5\0\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\71\1\0\3\10"+
    "\2\0\5\72\1\10\1\72\1\10\2\30\1\224\17\30"+
    "\2\10\1\72\1\0\1\71\5\0\5\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\65\1\71\1\0\3\10\2\0"+
    "\5\72\1\10\1\72\1\10\1\30\1\225\20\30\2\10"+
    "\1\72\1\0\1\71\5\0\5\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\65\1\71\1\0\3\10\2\0\5\72"+
    "\1\10\1\72\1\10\13\30\1\226\6\30\2\10\1\72"+
    "\1\0\1\71\5\0\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\65\1\71\1\0\3\10\2\0\5\72\1\10"+
    "\1\72\1\10\10\30\1\227\11\30\2\10\1\72\1\0"+
    "\1\71\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\13\30\1\230\6\30\2\10\1\72\1\0\1\71"+
    "\5\0\5\10\3\0\1\10\1\0\1\10\1\0\1\65"+
    "\1\71\1\0\3\10\2\0\5\72\1\10\1\72\1\10"+
    "\3\30\1\231\16\30\2\10\1\72\1\0\1\71\4\0"+
    "\1\232\70\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\13\30\1\233\6\30\2\10\1\72\1\0\1\71"+
    "\5\0\5\10\3\0\1\10\1\0\1\10\1\0\1\65"+
    "\1\71\1\0\3\10\2\0\1\234\4\72\1\10\1\72"+
    "\1\10\22\30\2\10\1\72\1\0\1\71\5\0\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\1\65\1\71\1\0"+
    "\3\10\2\0\5\72\1\10\1\72\1\10\4\30\1\235"+
    "\15\30\2\10\1\72\1\0\1\71\5\0\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\71\1\0\3\10"+
    "\2\0\5\72\1\10\1\72\1\10\1\236\21\30\2\10"+
    "\1\72\1\0\1\71\5\0\5\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\65\1\71\1\0\3\10\2\0\5\72"+
    "\1\10\1\72\1\10\4\30\1\237\15\30\2\10\1\72"+
    "\1\0\1\71\5\0\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\65\1\71\1\0\3\10\2\0\5\72\1\10"+
    "\1\72\1\10\10\30\1\240\11\30\2\10\1\72\1\0"+
    "\1\71\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\2\30\1\241\17\30\2\10\1\72\1\0\1\71"+
    "\5\0\5\10\3\0\1\10\1\0\1\10\1\0\1\65"+
    "\1\71\1\0\3\10\2\0\5\72\1\10\1\72\1\10"+
    "\17\30\1\242\2\30\2\10\1\72\1\0\1\71\5\0"+
    "\5\10\3\0\1\10\1\0\1\10\1\0\1\65\1\71"+
    "\1\0\3\10\2\0\5\72\1\10\1\72\1\10\17\30"+
    "\1\243\2\30\2\10\1\72\1\0\1\71\5\0\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\1\65\1\71\1\0"+
    "\3\10\2\0\5\72\1\10\1\72\1\10\4\30\1\244"+
    "\15\30\2\10\1\72\1\0\1\71\4\0\1\245\70\0"+
    "\5\10\3\0\1\10\1\0\1\10\1\0\1\65\1\71"+
    "\1\0\3\10\2\0\1\72\1\246\1\72\1\247\1\250"+
    "\1\10\1\72\1\10\22\125\2\10\1\72\1\0\1\71"+
    "\5\0\5\10\3\0\1\10\1\0\1\10\1\0\1\65"+
    "\1\71\1\0\3\10\2\0\5\72\1\10\1\72\1\10"+
    "\15\30\1\251\4\30\2\10\1\72\1\0\1\71\5\0"+
    "\5\10\3\0\1\10\1\0\1\10\1\0\1\65\1\71"+
    "\1\0\3\10\2\0\5\72\1\10\1\72\1\10\15\30"+
    "\1\252\4\30\2\10\1\72\1\0\1\71\5\0\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\1\65\1\71\1\0"+
    "\3\10\2\0\5\72\1\10\1\72\1\10\16\30\1\253"+
    "\3\30\2\10\1\72\1\0\1\71\5\0\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\71\1\0\3\10"+
    "\2\0\5\72\1\10\1\72\1\10\15\30\1\254\4\30"+
    "\2\10\1\72\1\0\1\71\5\0\5\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\65\1\71\1\0\3\10\2\0"+
    "\5\72\1\10\1\72\1\10\10\30\1\255\11\30\2\10"+
    "\1\72\1\0\1\71\5\0\5\10\3\0\1\10\1\0"+
    "\1\10\1\0\1\65\1\71\1\0\3\10\2\0\5\72"+
    "\1\10\1\72\1\10\12\30\1\256\7\30\2\10\1\72"+
    "\1\0\1\71\5\0\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\65\1\71\1\0\3\10\2\0\5\72\1\10"+
    "\1\72\1\10\4\30\1\257\15\30\2\10\1\72\1\0"+
    "\1\71\5\0\5\10\3\0\1\10\1\0\1\10\1\0"+
    "\1\65\1\71\1\0\3\10\2\0\5\72\1\10\1\72"+
    "\1\10\15\30\1\163\4\30\2\10\1\72\1\0\1\71"+
    "\5\0\5\10\3\0\1\10\1\0\1\10\1\0\1\65"+
    "\1\71\1\0\3\10\2\0\5\72\1\10\1\72\1\10"+
    "\14\125\1\260\5\125\2\10\1\72\1\0\1\71\5\0"+
    "\5\10\3\0\1\10\1\0\1\10\1\0\1\65\1\71"+
    "\1\0\3\10\2\0\5\72\1\10\1\72\1\10\13\125"+
    "\1\261\6\125\2\10\1\72\1\0\1\71\5\0\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\1\65\1\71\1\0"+
    "\3\10\2\0\5\72\1\10\1\72\1\10\4\125\1\262"+
    "\15\125\2\10\1\72\1\0\1\71\4\0\1\263\5\10"+
    "\3\0\1\10\1\0\1\10\1\0\1\65\1\71\1\0"+
    "\3\10\2\0\5\72\1\10\1\72\1\10\22\30\2\10"+
    "\1\72\1\0\1\71\4\0\1\264\5\10\3\0\1\10"+
    "\1\0\1\10\1\0\1\65\1\71\1\0\3\10\2\0"+
    "\5\72\1\10\1\72\1\10\22\30\2\10\1\72\1\0"+
    "\1\71\4\0\1\265\5\10\3\0\1\10\1\0\1\10"+
    "\1\0\1\65\1\71\1\0\3\10\2\0\5\72\1\10"+
    "\1\72\1\10\22\30\2\10\1\72\1\0\1\71\5\0"+
    "\5\10\3\0\1\10\1\0\1\10\1\0\1\65\1\71"+
    "\1\0\3\10\2\0\5\72\1\10\1\72\1\10\1\266"+
    "\21\30\2\10\1\72\1\0\1\71\5\0\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\71\1\0\3\10"+
    "\2\0\5\72\1\10\1\72\1\10\14\30\1\267\5\30"+
    "\2\10\1\72\1\0\1\71\22\0\1\125\6\0\5\125"+
    "\1\0\1\125\1\0\11\125\1\270\10\125\2\0\1\125"+
    "\1\0\1\125\22\0\1\125\6\0\5\125\1\0\1\125"+
    "\1\0\17\125\1\271\2\125\2\0\1\125\1\0\1\125"+
    "\22\0\1\125\6\0\5\125\1\0\1\125\1\0\1\272"+
    "\21\125\2\0\1\125\1\0\1\125\5\0\5\10\3\0"+
    "\1\10\1\0\1\10\1\0\1\65\1\71\1\0\3\10"+
    "\2\0\5\72\1\10\1\72\1\10\15\30\1\273\4\30"+
    "\2\10\1\72\1\0\1\71\22\0\1\125\6\0\5\125"+
    "\1\0\1\125\1\0\4\125\1\274\15\125\2\0\1\125"+
    "\1\0\1\125\22\0\1\125\6\0\5\125\1\0\1\125"+
    "\1\0\4\125\1\275\15\125\2\0\1\125\1\0\1\125"+
    "\22\0\1\125\6\0\5\125\1\0\1\125\1\0\11\125"+
    "\1\276\10\125\2\0\1\125\1\0\1\125\4\0\1\277"+
    "\5\10\3\0\1\10\1\0\1\10\1\0\1\65\1\71"+
    "\1\0\3\10\2\0\5\72\1\10\1\72\1\10\22\30"+
    "\2\10\1\72\1\0\1\71\22\0\1\125\6\0\5\125"+
    "\1\0\1\125\1\0\1\300\21\125\2\0\1\125\1\0"+
    "\1\125\22\0\1\125\6\0\5\125\1\0\1\125\1\0"+
    "\15\125\1\301\4\125\2\0\1\125\1\0\1\125\22\0"+
    "\1\125\6\0\5\125\1\0\1\125\1\0\13\125\1\302"+
    "\6\125\2\0\1\125\1\0\1\125\22\0\1\125\6\0"+
    "\5\125\1\0\1\125\1\0\14\125\1\303\5\125\2\0"+
    "\1\125\1\0\1\125\22\0\1\125\6\0\5\125\1\0"+
    "\1\125\1\0\14\125\1\304\5\125\2\0\1\125\1\0"+
    "\1\125";

  private static int [] zzUnpackTrans() {
    int [] result = new int[8848];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\2\11\6\1\3\11\1\1\1\11\1\1\1\11"+
    "\2\1\1\11\22\1\1\0\2\1\1\0\10\1\1\0"+
    "\31\1\1\0\1\11\1\1\3\0\22\1\1\11\30\1"+
    "\1\0\14\1\1\11\2\1\1\0\14\1\1\0\30\1"+
    "\3\11\11\1\1\11\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[196];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;
    public int linea;


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  intermedio(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length * 2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException(
          "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE) {
      zzBuffer = new char[ZZ_BUFFERSIZE];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return new Symbol(sym.EOF );
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { 
            }
            // fall through
          case 48: break;
          case 2:
            { System.out.println("Error verificar . "+yytext());
                        return new Symbol(sym.error);
            }
            // fall through
          case 49: break;
          case 3:
            { return new Symbol(sym.salto,yytext());
            }
            // fall through
          case 50: break;
          case 4:
            { return new Symbol(sym.newline,yytext());
            }
            // fall through
          case 51: break;
          case 5:
            { return new Symbol(sym.libre,yytext());
            }
            // fall through
          case 52: break;
          case 6:
            { lexeme=yytext();
                        return new Symbol(sym.error);
            }
            // fall through
          case 53: break;
          case 7:
            { lexeme=yytext(); 
                          return new Symbol(sym.opnum,yytext());
            }
            // fall through
          case 54: break;
          case 8:
            { return new Symbol(sym.para,yytext());
            }
            // fall through
          case 55: break;
          case 9:
            { return new Symbol(sym.parb,yytext());
            }
            // fall through
          case 56: break;
          case 10:
            { lexeme=yytext(); 
                        return new Symbol(sym.coma,yytext());
            }
            // fall through
          case 57: break;
          case 11:
            { lexeme=yytext(); 
                        return new Symbol(sym.pun,yytext());
            }
            // fall through
          case 58: break;
          case 12:
            { lexeme=yytext();   return new Symbol(sym.entero,Integer.parseInt(yytext()));
            }
            // fall through
          case 59: break;
          case 13:
            { lexeme=yytext(); 
                         return  new Symbol(sym.fin_de_linea,yytext());
            }
            // fall through
          case 60: break;
          case 14:
            { lexeme=yytext(); 
                          return new Symbol(sym.condicionales,yytext());
            }
            // fall through
          case 61: break;
          case 15:
            { lexeme=yytext(); 
                        return new Symbol(sym.asignacion,yytext());
            }
            // fall through
          case 62: break;
          case 16:
            { lexeme=yytext(); return new Symbol(sym.IDmayu,yytext());
            }
            // fall through
          case 63: break;
          case 17:
            { lexeme=yytext();  
                        System.out.println("Error verificar "+yytext());
                        return new Symbol(sym.error);
            }
            // fall through
          case 64: break;
          case 18:
            { lexeme=yytext(); 
                         return new Symbol(sym.identificador,yytext());
            }
            // fall through
          case 65: break;
          case 19:
            { lexeme=yytext(); 
                          return new Symbol(sym.opcadnum,yytext());
            }
            // fall through
          case 66: break;
          case 20:
            { lexeme=yytext();  return new Symbol(sym.cadena,yytext());
            }
            // fall through
          case 67: break;
          case 21:
            { lexeme=yytext(); 
                          return new Symbol(sym.aumento,yytext());
            }
            // fall through
          case 68: break;
          case 22:
            { lexeme=yytext();
                        System.out.println("Error verificar "+yytext());
                        return new Symbol(sym.error);
            }
            // fall through
          case 69: break;
          case 23:
            { lexeme=yytext();  return new Symbol(sym.comentario,yytext());
            }
            // fall through
          case 70: break;
          case 24:
            { lexeme=yytext();  return new Symbol(sym.real,Double.parseDouble(yytext()));
            }
            // fall through
          case 71: break;
          case 25:
            { lexeme=yytext(); 
                         return new Symbol(sym.ifs,yytext());
            }
            // fall through
          case 72: break;
          case 26:
            { return new Symbol(sym.tabu,yytext());
            }
            // fall through
          case 73: break;
          case 27:
            { lexeme=yytext();  return new Symbol(sym.comentarios,yytext());
            }
            // fall through
          case 74: break;
          case 28:
            { lexeme=yytext(); 
                        return new Symbol(sym.salida,yytext());
            }
            // fall through
          case 75: break;
          case 29:
            { lexeme=yytext(); return new Symbol(sym.tipo_ca8,yytext());
            }
            // fall through
          case 76: break;
          case 30:
            { lexeme=yytext(); return new Symbol(sym.tipo_real,yytext());
            }
            // fall through
          case 77: break;
          case 31:
            { lexeme=yytext(); return new Symbol(sym.tipo_ca4,yytext());
            }
            // fall through
          case 78: break;
          case 32:
            { lexeme=yytext();  
                        return new Symbol(sym.boleano,yytext());
            }
            // fall through
          case 79: break;
          case 33:
            { lexeme=yytext(); 
                         return new Symbol(sym.els,yytext());
            }
            // fall through
          case 80: break;
          case 34:
            { lexeme=yytext(); return new Symbol(sym.tipo_cadena,yytext());
            }
            // fall through
          case 81: break;
          case 35:
            { lexeme=yytext(); return new Symbol(sym.tipo_ca5,yytext());
            }
            // fall through
          case 82: break;
          case 36:
            { lexeme=yytext(); return new Symbol(sym.tipo_ent,yytext());
            }
            // fall through
          case 83: break;
          case 37:
            { lexeme=yytext(); return new Symbol(sym.tipo_bol,yytext());
            }
            // fall through
          case 84: break;
          case 38:
            { lexeme=yytext(); 
                        return new Symbol(sym.entrada,yytext());
            }
            // fall through
          case 85: break;
          case 39:
            { lexeme=yytext(); return new Symbol(sym.tipo_ca6,yytext());
            }
            // fall through
          case 86: break;
          case 40:
            { lexeme=yytext(); 
                        linea= yyline; 
                        return new Symbol(sym.retornar,yytext());
            }
            // fall through
          case 87: break;
          case 41:
            { lexeme=yytext(); 
                         return new Symbol(sym.borrar,yytext());
            }
            // fall through
          case 88: break;
          case 42:
            { lexeme=yytext(); 
                         return new Symbol(sym.entoncess,yytext());
            }
            // fall through
          case 89: break;
          case 43:
            { lexeme=yytext(); return new Symbol(sym.tipo_ca7,yytext());
            }
            // fall through
          case 90: break;
          case 44:
            { lexeme=yytext(); return new Symbol(sym.tipo_ca2,yytext());
            }
            // fall through
          case 91: break;
          case 45:
            { lexeme=yytext(); 
                         return new Symbol(sym.insta,yytext());
            }
            // fall through
          case 92: break;
          case 46:
            { lexeme=yytext(); return new Symbol(sym.tipo_ca,yytext());
            }
            // fall through
          case 93: break;
          case 47:
            { lexeme=yytext(); return new Symbol(sym.tipo_ca3,yytext());
            }
            // fall through
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
