package gt.edu.url.compiladores.loop.interprete.loop.interprete;
import java_cup.runtime.Symbol;


terminal Integer NUM;
terminal COMA;

non terminal Integer S;

S ::=  NUM:n COMA S:s
        {:
            Integer resultado=s + n;
            System.out.println("SYN: "+resultado);
            RESULT=resultado;
        :}
        | NUM:n
        {: 
            System.out.println("SYN: "+n);
            RESULT=n;
        :};


