/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gt.edu.url.compiladores.loop.interprete;

import javax.swing.JFrame;

/**
 *
 * @author Enrique Castañeda <enrique7cp@gmail.com>
 */
public class LOOPInterfaz extends javax.swing.JFrame {

    /**
     * Creates new form LOOPInterfaz
     */
    public LOOPInterfaz() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JPanel();
        pnlSalida = new javax.swing.JPanel();
        spSalida = new javax.swing.JScrollPane();
        txaSalida = new javax.swing.JTextArea();
        pnlControl = new javax.swing.JPanel();
        btnRun = new javax.swing.JButton();
        pnlCodigo = new javax.swing.JPanel();
        spCodigo = new javax.swing.JScrollPane();
        txaCodigo = new javax.swing.JTextArea();
        mbPrincipal = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        miAbrirArchivo = new javax.swing.JMenuItem();
        miNuevoArchivo = new javax.swing.JMenuItem();
        miGuardarArchivo = new javax.swing.JMenuItem();
        mConfiguracion = new javax.swing.JMenu();
        mAbout = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOOP");

        pnlPrincipal.setBackground(new java.awt.Color(38, 39, 40));
        pnlPrincipal.setForeground(new java.awt.Color(60, 63, 65));

        pnlSalida.setBackground(new java.awt.Color(38, 39, 40));

        txaSalida.setBackground(new java.awt.Color(38, 39, 45));
        txaSalida.setColumns(20);
        txaSalida.setFont(new java.awt.Font("FreeMono", 0, 16)); // NOI18N
        txaSalida.setForeground(new java.awt.Color(0, 153, 0));
        txaSalida.setRows(5);
        txaSalida.setText("Salida:");
        spSalida.setViewportView(txaSalida);

        javax.swing.GroupLayout pnlSalidaLayout = new javax.swing.GroupLayout(pnlSalida);
        pnlSalida.setLayout(pnlSalidaLayout);
        pnlSalidaLayout.setHorizontalGroup(
            pnlSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spSalida, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlSalidaLayout.setVerticalGroup(
            pnlSalidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSalidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spSalida)
                .addContainerGap())
        );

        pnlControl.setBackground(new java.awt.Color(25, 25, 25));
        pnlControl.setForeground(new java.awt.Color(60, 63, 65));

        btnRun.setBackground(new java.awt.Color(25, 25, 25));
        btnRun.setText("RUN");
        btnRun.setToolTipText("Correr programa");
        btnRun.setBorder(null);

        javax.swing.GroupLayout pnlControlLayout = new javax.swing.GroupLayout(pnlControl);
        pnlControl.setLayout(pnlControlLayout);
        pnlControlLayout.setHorizontalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlControlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRun, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlControlLayout.setVerticalGroup(
            pnlControlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlControlLayout.createSequentialGroup()
                .addContainerGap(382, Short.MAX_VALUE)
                .addComponent(btnRun)
                .addGap(91, 91, 91))
        );

        pnlCodigo.setBackground(new java.awt.Color(38, 39, 40));

        txaCodigo.setBackground(new java.awt.Color(38, 39, 48));
        txaCodigo.setColumns(20);
        txaCodigo.setFont(new java.awt.Font("FreeMono", 0, 16)); // NOI18N
        txaCodigo.setForeground(new java.awt.Color(255, 255, 255));
        txaCodigo.setRows(5);
        txaCodigo.setCaretColor(new java.awt.Color(255, 255, 255));
        spCodigo.setViewportView(txaCodigo);

        javax.swing.GroupLayout pnlCodigoLayout = new javax.swing.GroupLayout(pnlCodigo);
        pnlCodigo.setLayout(pnlCodigoLayout);
        pnlCodigoLayout.setHorizontalGroup(
            pnlCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCodigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spCodigo)
                .addContainerGap())
        );
        pnlCodigoLayout.setVerticalGroup(
            pnlCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCodigoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spCodigo)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlPrincipalLayout = new javax.swing.GroupLayout(pnlPrincipal);
        pnlPrincipal.setLayout(pnlPrincipalLayout);
        pnlPrincipalLayout.setHorizontalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPrincipalLayout.createSequentialGroup()
                .addComponent(pnlControl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlSalida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlPrincipalLayout.setVerticalGroup(
            pnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLayout.createSequentialGroup()
                .addComponent(pnlCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSalida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pnlControl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        mArchivo.setText("Archivo");
        mArchivo.setFont(new java.awt.Font("FreeMono", 0, 16)); // NOI18N

        miAbrirArchivo.setFont(new java.awt.Font("FreeMono", 0, 15)); // NOI18N
        miAbrirArchivo.setText("Abrir Archivo");
        mArchivo.add(miAbrirArchivo);

        miNuevoArchivo.setFont(new java.awt.Font("FreeMono", 0, 15)); // NOI18N
        miNuevoArchivo.setText("Nuevo Archivo");
        mArchivo.add(miNuevoArchivo);

        miGuardarArchivo.setFont(new java.awt.Font("FreeMono", 0, 15)); // NOI18N
        miGuardarArchivo.setText("Guardar");
        mArchivo.add(miGuardarArchivo);

        mbPrincipal.add(mArchivo);

        mConfiguracion.setText("Configuración");
        mConfiguracion.setFont(new java.awt.Font("FreeMono", 0, 16)); // NOI18N
        mbPrincipal.add(mConfiguracion);

        mAbout.setText("About");
        mAbout.setFont(new java.awt.Font("FreeMono", 0, 16)); // NOI18N
        mbPrincipal.add(mAbout);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOOPInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOOPInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOOPInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOOPInterfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOOPInterfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRun;
    private javax.swing.JMenu mAbout;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mConfiguracion;
    private javax.swing.JMenuBar mbPrincipal;
    private javax.swing.JMenuItem miAbrirArchivo;
    private javax.swing.JMenuItem miGuardarArchivo;
    private javax.swing.JMenuItem miNuevoArchivo;
    private javax.swing.JPanel pnlCodigo;
    private javax.swing.JPanel pnlControl;
    private javax.swing.JPanel pnlPrincipal;
    private javax.swing.JPanel pnlSalida;
    private javax.swing.JScrollPane spCodigo;
    private javax.swing.JScrollPane spSalida;
    private javax.swing.JTextArea txaCodigo;
    private javax.swing.JTextArea txaSalida;
    // End of variables declaration//GEN-END:variables
}
